<%@ Page Title="" Language="C#" MasterPageFile="~/design/MasterPage.master" AutoEventWireup="true" CodeFile="Holiday2013.aspx.cs" Inherits="Holiday2013" %>
<%@ Import Namespace="Artisteer" %>
<%@ Register TagPrefix="artisteer" Namespace="Artisteer" %>
<%@ Register TagPrefix="art" TagName="DefaultMenu" Src="DefaultMenu.ascx" %> 
<%@ Register TagPrefix="art" TagName="DefaultHeader" Src="DefaultHeader.ascx" %> 
<%@ Register TagPrefix="art" TagName="DefaultSidebar1" Src="DefaultSidebar1.ascx" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajax" %>          

<asp:Content ID="PageTitle" ContentPlaceHolderID="TitleContentPlaceHolder" Runat="Server">
    Community Action, Inc.
</asp:Content>

<asp:Content ID="HeaderContent" ContentPlaceHolderID="HeaderContentPlaceHolder" Runat="Server">
    <art:DefaultHeader ID="DefaultHeader" runat="server" />
</asp:Content>
<asp:Content ID="MenuContent" ContentPlaceHolderID="MenuContentPlaceHolder" Runat="Server">
    <art:DefaultMenu ID="DefaultMenuContent" runat="server" />
</asp:Content>
<asp:Content ID="SideBar1" ContentPlaceHolderID="Sidebar1ContentPlaceHolder" Runat="Server">
    <art:DefaultSidebar1 ID="DefaultSidebar1Content" runat="server" />
</asp:Content>

<asp:Content ID="SheetContent" ContentPlaceHolderID="SheetContentPlaceHolder" Runat="Server">
    <ajax:ToolkitScriptManager ID="tsm" runat="server" />
    <asp:UpdatePanel ID="PageUpdatePanel" runat="server">
        <ContentTemplate>
            <br />
            <asp:Panel ID="IntroPanel" runat="server" style="background-color:#D9D9D9;">
                <asp:Label ID="lblIntro" runat="server" Text="Please sign up for the Holiday Party" />
            </asp:Panel>
            <asp:GridView ID="grdHoliday" runat="server" DataKeyNames="ID" AllowSorting="true"
                CellPadding="0" ShowFooter="true" Width="100%"
                AutoGenerateDeleteButton="False" AutoGenerateSelectButton="false" 
                AutoGenerateEditButton="False" style="background-color:#D9D9D9;"
                DataSourceID="srcHoliday" AutoGenerateColumns="false">
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="lbEdit" runat="server" CommandName="Edit" Text="Edit" />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:LinkButton ID="lbUpdate" runat="server" CommandName="Update" Text="Update" />
                            <asp:LinkButton ID="lbCancel" runat="server" CommandName="Cancel" Text="Cancel" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton ID="lbInsert" runat="server" OnClick="grdHoliday_Insert" Text="Insert" /> 
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField Visible="false">
                        <ItemTemplate>
                            <asp:Label id="lblID" runat="Server" Text='<%#Bind("ID") %>' />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:Label id="lblID" runat="Server" Text='<%#Bind("ID") %>' />
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Name">
                        <ItemTemplate>
                            <asp:Label id="lblName" runat="Server" Text='<%#Bind("Name") %>' />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="txtName" runat="Server" Text='<%#Bind("Name") %>' Width="98%"/>
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox id="txtName" runat="Server" Text='<%#Bind("Name") %>' Width="98%" />
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Covered Dish">
                        <ItemTemplate>
                            <asp:Label id="lblCoveredDish" runat="server" Text='<%#Bind ("CoveredDish") %>' />
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="txtCoveredDish" runat="server" Text='<%#Bind ("CoveredDish") %>' Width="98%" />
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox id="txtCoveredDish" runat="server" Text='<%#Bind ("CoveredDish") %>' Width="98%" />
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Gift Exchange" >
                        <ItemTemplate>
                            <asp:CheckBox ID="cbGiftExchange" runat="server" Checked='<%#Bind ("GiftExchange") %>' Enabled="false" Width="10%"/>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:CheckBox ID="cbGiftExchange" runat="server" Checked='<%#Bind ("GiftExchange") %>'/>
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:CheckBox ID="cbGiftExchange" runat="server" Checked='<%#Bind ("GiftExchange") %>'/>
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="srcHoliday" runat="server" ConnectionString="<%$ ConnectionStrings:CAI %>"
                SelectCommand="SELECT ID, Name, CoveredDish, GiftExchange FROM HOLIDAY_2013"
                UpdateCommand="UPDATE HOLIDAY_2013 SET Name=@Name, CoveredDish=@CoveredDish, GiftExchange=@GiftExchange WHERE ID=@ID" />
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>